# Generated by Django 2.1.5 on 2019-03-16 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fq1', models.CharField(default='Clarity About the Topic ', max_length=1000)),
                ('fq2', models.CharField(default='Regularity And Punctuality of the Faculty ', max_length=1000)),
                ('fq3', models.CharField(default='Pace Of Teaching ', max_length=1000)),
                ('topic1', models.CharField(default='', max_length=1000)),
                ('topic2', models.CharField(default='', max_length=1000)),
                ('topic3', models.CharField(default='', max_length=1000)),
                ('topic4', models.CharField(default='', max_length=1000)),
                ('topic5', models.CharField(default='', max_length=1000)),
            ],
        ),
    ]
