# Generated by Django 2.1.5 on 2019-03-16 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0002_auto_20190316_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='name',
        ),
    ]
