# Generated by Django 2.1.5 on 2019-03-16 10:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissiondata',
            name='q1',
            field=models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='submissiondata',
            name='q2',
            field=models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='submissiondata',
            name='q3',
            field=models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='submissiondata',
            name='q4',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='submissiondata',
            name='q5',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='sdata',
            name='phone',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(9999999999)]),
        ),
    ]
