# Generated by Django 2.1.5 on 2019-03-16 17:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20190316_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissiondata',
            name='q5',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(1)]),
        ),
    ]
