# Generated by Django 2.1.5 on 2019-03-16 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20190316_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissiondata',
            name='q5text',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
